config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'general_shopping_lists/index'
  get 'shopping_list/:recipe_id/:inventory_id', to: 'shopping_list#index', as: :shopping_list
  devise_for :users
  root 'recipes#index'
  resources :recipes
  resources :food_recipes
  resources :foods
  resources :public_recipes
  resources :inventories
  resources :inventory_food
  resources :general_shopping_lists, only: %i[index], path: '/general_shopping_list'
  resources :shopping_list
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user

  has_many :inventory_foods

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
    @inventories = if current_user.nil?
                     []
                   else
                     @current_user.inventories
                   end
  end

  def new
    @inventory = Inventory.new
  end

  def show
    @inventory = Inventory.find(params[:id])
  end

  def create
    @user = current_user
    @inventory = Inventory.new(inventory_params)
    @inventory.user_id = @user.id
    respond_to do |format|
      format.html do
        if @inventory.save
          flash[:success] = 'Inventory saved successfully'
          redirect_to inventories_path
        else
          flash[:error] = 'Error: Inventory could not be saved'
          redirect_to new_inventory_url(@user)
        end
      end
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    @inventory.destroy
    flash[:notice] = 'Inventory was deleted successfully.'
    redirect_to inventories_path
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name, :string)
  end
end

app/views/inventories/index.html.erb
<section class='recipes'>
  <% if @current_user.nil? %>
    <h2>Welcome, kindly login to see the list!</h2>
  <% else %>
  <h1 class="title">Your Inventories</h1>
  <% if @inventories.blank? %>
    <h2>No inventories found!<h2>
  <% else %>
    <% @inventories.each do |inventory| %>
      <article class="card">
        <div>
          <h2><%= link_to inventory.name, inventory_path(inventory.id), method: :get, class:"link" %></h2>
          <% if can? :destroy, inventory %>
            <%= button_to 'Remove', inventory_path(inventory.id), method: :delete, class:'delete-btn' %>
          <% end %>
        </div>
        <div>
          <p><%= inventory.name %></p>
        </div>
      </article>
    <% end %>  
  <% end %>
  <%= button_to 'Add new inventory', new_inventory_path, method: :get, class:"add-recipe" %>
<% end %>
</section>

app/views/inventories/new.html.erb
<div>
    <div>
        <%= link_to 'Inventories', inventories_path %>
    </div>
    <h2>Please add an inventory</h2>
    <% if @inventory.errors.any? %>
    <h2>Unable to save inventory.</h2>
    <ul>
      <% @inventory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
    <%= form_with model: @inventory, url: inventories_path, method: :post do |f| %>
        <p class="sname">
            <%= f.label :name %><br>
            <%= f.text_field :name, placeholder: 'Inventory name' %><br>
        </p>

        <p class="sname">
            <%= f.label :description %><br>
            <%= f.text_area :description, placeholder: 'Inventory Description' %><br>
        </p>

        <p class="sname">
            <%= f.submit "Add Inventory" %>
        </p>
    <% end %>
</div>

app/views/inventories/show.html.erb
<section class = 'recipe-description'>
  <div class="path">
    <%= link_to 'Back', inventories_path, class:"link back" %>
  </div>

 <h2 class="names"><%= @inventory.name %></h2>
  <div class="holder">
    <p class="prep">Inventory Description: <%= @inventory.name %></p>
   
    <div class='add-btn'><%= link_to 'Add Food',  new_food_path, class:"add-food" %></div>
     <% if can? :create, @food %>
     <% end %>
   
  </div>
</section>