config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'general_shopping_lists/index'
  get 'shopping_list/:recipe_id/:inventory_id', to: 'shopping_list#index', as: :shopping_list
  devise_for :users
  root 'recipes#index'
  resources :recipes
  resources :food_recipes
  resources :foods
  resources :public_recipes
  resources :inventories
  resources :inventory_food
  resources :general_shopping_lists, only: %i[index], path: '/general_shopping_list'
  resources :shopping_list
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  before_action :authenticate_user!
  def new
    @inventories = if current_user.nil?
                     []
                   else
                     @current_user.inventories
                   end
  end

  def index
    @total_price = 0
    @foods = current_user.foods.includes(:food_recipes).map do |food|
      next if food.food_recipes.empty?

      total_quantity = food.food_recipes.sum(:quantity)
      price = total_quantity * food.price
      @total_price += price

      {
        name: food.name,
        measurement_unit: food.measurement_unit,
        price: food.price
      }
    end.compact
    @recipes = current_user.recipes
    @inventories = current_user.inventories
  end
end

app/helpers/shopping_list_helper.rb
module ShoppingListHelper
end

app/views/shopping_list/index.html.erb
<section id="shopping-list">
  <h2>Shopping List</h2>
  <div class="summary">
    <div>
      <h3>Amount of food items to buy: <%= @foods.length %></h3>
      <h3>
        Total value of food needed: $<%= number_with_precision(@total_price, precision: 2) %>
      </h3>
    </div>

    <div>
      <h3>Recipe: <%= link_to @recipes.name, recipes_path(@recipe) %>
      <h3>Inventory: <%= link_to @inventories.name, inventory_path(@inventories)  %>
    </div>
  </div>

    <table class="ingredients-table">
      <thead>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr>
            <td class="food-name"><%= food[:name] %></td>
            <td> <%= "#{food[:total_quantity]}""#{food[:measurement_unit]}" %></td>
            <td>$<%= number_with_precision(food[:price], precision: 2) %></td> 
          </tr>
        <% end %>
      </tbody>
    </table>
</section>

app/views/shopping_list/new.html.erb
<section>
<h1>Generate Shopping List</h1>

<div>
  <h3> Choose an inventory to use</h3>

  <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              Select Inventory
            </button>
            <ul class="dropdown-menu">
              <% if @inventories.count > 0 %>
                <% @inventories.each do |inventory| %>
                  <li>
                    <%= link_to inventory.name, shopping_list_index_path, class: 'dropdown-item' %>
                  </li>
                <% end %>
              <% else %>
                <p>Your inventory is empty</p>
              <% end %>
            </ul>
  </div>
</div>
</section>