config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'general_shopping_lists/index'
  get 'shopping_list/:recipe_id/:inventory_id', to: 'shopping_list#index', as: :shopping_list
  devise_for :users
  root 'recipes#index'
  resources :recipes
  resources :food_recipes
  resources :foods
  resources :public_recipes
  resources :inventories
  resources :inventory_food
  resources :general_shopping_lists, only: %i[index], path: '/general_shopping_list'
  resources :shopping_list
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :food_recipes, dependent: :destroy
  has_many :foods, through: :food_recipes

  validates :name, presence: true, length: { minimum: 3, maximum: 250 }
  validates :preparation_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :description, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = if current_user.nil?
                 []
               else
                 @current_user.recipes
               end
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.find(params[:id])
    @food_recipes = FoodRecipe.includes(:food).where(recipe_id: @recipe.id)
  end

  def create
    user = current_user
    recipe = Recipe.new(params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time,
                                                       :public))
    recipe.user = user
    respond_to do |format|
      format.html do
        if recipe.save
          flash[:success] = 'Recipe saved successfully'
          redirect_to recipes_url
        else
          flash[:error] = 'Error: recipe could not be saved'
          redirect_to new_recipe_url
        end
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = 'Recipe was deleted successfully.'
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/views/recipes/index.html.erb
<section class='recipes'>
  <% if @current_user.nil? %>
  <h2>You need to first login to see the list!</h2>
<% else %>
  <h1 class="title">Your recipes</h1>
  <% if @recipes.blank? %>
    <h2>No recipes yet!<h2>
  <% else %>
    <% @recipes.each do |recipe| %>
      <article class="card">
        <div>
          <h2><%= link_to recipe.name, recipe_path(recipe.id), method: :get,class:"link" %></h2>
          <% if can? :destroy, recipe %>
            <%= button_to 'Remove', recipe_path(recipe.id), method: :delete, class:'delete-btn' %>
          <% end %>
        </div>
        <div>
          <p><%= recipe.description %></p>
        </div>
      </article>
    <% end %>  
  <% end %>
  <%= button_to 'Add new recipe', new_recipe_path, method: :get, class:"add-recipe" %>
<% end %>
</section>

app/views/recipes/new.html.erb
<div>
    <div>
        <%= link_to ' Recipes', recipes_path %>
    </div>
    <h2>Add new recipe</h2>
    <% if @recipe.errors.any? %>
    <h2>Your recipe couldn not be saved, here is why</h2>
    <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
    <%= form_with model: @recipe, url: recipes_path, method: :post do |f| %>
        <p class="sname">
            <%= f.label :name %><br>
            <%= f.text_field :name, placeholder: 'Recipe name' %><br>
        </p>

        <p class="sname">
            <%= f.label :description %><br>
            <%= f.text_area :description, placeholder: 'Cooking steps' %><br>
        </p>

        <p class="sname">
            <%= f.label :preparation_time %><br>
            <%= f.number_field :preparation_time, step: :any, placeholder: '00:00' %><br>
        </p>

        <p class="sname">
            <%= f.label :cooking_time %><br>
            <%= f.number_field :cooking_time, step: :any, placeholder: '00:00' %><br>
        </p>

        <p class="sname">
            <%= f.label :public %><br>
            <%= f.check_box :public %><br>
        </p>

        <p class="sname">
            <%= f.submit "Add Recipe" %>
        </p>
    <% end %>
</div>

app/views/recipes/show.html.erb
<section class = 'recipe-description'>
  <div class="path">
    <%= link_to 'Back', recipes_path, class:"link back" %>
  </div>

 <h2 class="names"><%= @recipe.name %></h2>
  <div class="holder">
    <div>
    <div class='public'>
      <div>
    <p class="prep">Preparation time: <%= @recipe.preparation_time %>hours</p>
    <p class="cook">Cooking time: <%= @recipe.cooking_time %>hours</p>
    <p class="steps">Cooking steps: <%= @recipe.description %></p>
    </div>
    <div class='public-btn'><h3>Public: <%= @recipe.public %></h3></div>
    </div> 
   
     <% if can? :create, @food %>
       <div class ='btn-div'>
        <div class='add-btn'><%= link_to 'Generate Shopping List', new_shopping_list_path, class:"add-food" %></div>
         <%= link_to 'Add ingredient', new_food_recipe_path(recipe_id: @recipe.id), method: :get, class:'recipe-btn' %>
       </div>
     <% end %>
    </div>
   
  </div>
</section>