config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'general_shopping_lists/index'
  get 'shopping_list/:recipe_id/:inventory_id', to: 'shopping_list#index', as: :shopping_list
  devise_for :users
  root 'recipes#index'
  resources :recipes
  resources :food_recipes
  resources :foods
  resources :public_recipes
  resources :inventories
  resources :inventory_food
  resources :general_shopping_lists, only: %i[index], path: '/general_shopping_list'
  resources :shopping_list
end

app/models/food_recipe.rb
class FoodRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/food_recipes_controller.rb
class FoodRecipesController < ApplicationController
  def new
    @foods = Food.current_user.foods
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    food_recipe = FoodRecipe.new(params.require(:recipe_food).permit(:food_id, :quantity))
    food_recipe.recipe = @recipe
    respond_to do |format|
      format.html do
        if food_recipe.save
          flash[:success] = 'Ingredient saved successfully'
          redirect_to recipe_url(@recipe.id)
        else
          flash[:error] = 'Error: Ingredient could not be saved'
          redirect_to new_recipe_food_recipe_url
        end
      end
    end
  end

  def destroy
    @food_recipe = FoodRecipe.find(params[:id])
    @recipe = @food_recipe.recipe
    @food_recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipe_url(@recipe), notice: 'Food recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def food_recipe_params
    params.require(:food_recipe).permit(:quantity)
  end
end

app/helpers/food_recipes_helper.rb
module FoodRecipesHelper
end

app/views/food_recipes/new.html.erb
<%puts params%>
<div>
  <div>
  <div class="emm">
      <%= link_to '< Recipes', recipes_path(params[:recipe_id])%>
    </div> 
    <div>
      <%=form_with url: food_recipes_url(recipe_id: params[:recipe_id]), scope: :recipe_food do |f| %>
        <div>
          <div class="sfood">
            <%= f.select :food_id, @foods.collect { |food| [food.name, food.id] }, :prompt => 'Select an Ingredient', class: 'sinn', required: true %>
          </div>
          <div>
            <%= f.label :quantity, 'Quantity:' %>
            <%= f.number_field :quantity, step: :any, required: true, class: 'numbr'%>
          </div>
        </div>
        <div>
          <%= f.submit "Add Ingredient", class: 'iadd'%>
        </div> 
      <% end %>
    </div>
  </div>
</div>